# Generated by Django 5.2.2 on 2025-06-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='category_images/')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
